# Data Driven Science and Engineering

## Cap 01 - SVD

In [10]:
import numpy as np
X = np.random.rand(5,3)  #create ramdom data matrix
U, S, V = np.linalg.svd(X, full_matrices=True)  #Full SVD
Uhat, Shat, Vhat = np.linalg.svd(X, full_matrices=False) #Economy SVD

### Full SVD

In [11]:
print(U)

[[-0.42662315 -0.40140197  0.73417878 -0.3157909  -0.13463565]
 [-0.3761024   0.62021859 -0.12876473 -0.32734165 -0.5917288 ]
 [-0.59688787 -0.446464   -0.4456639   0.43731758 -0.23352044]
 [-0.05015557  0.38324199  0.49400279  0.77223409 -0.10112247]
 [-0.56369226  0.32863481 -0.04178621 -0.0743734   0.7529759 ]]


In [12]:
print(S)

[2.08109217 0.75796378 0.20720474]


In [13]:
print(V)

[[-0.28229277 -0.65836189 -0.697761  ]
 [ 0.89507686  0.08095238 -0.43850213]
 [ 0.34517851 -0.74833571  0.56643223]]


### Economy SVD

In [14]:
print(Uhat)

[[-0.42662315 -0.40140197  0.73417878]
 [-0.3761024   0.62021859 -0.12876473]
 [-0.59688787 -0.446464   -0.4456639 ]
 [-0.05015557  0.38324199  0.49400279]
 [-0.56369226  0.32863481 -0.04178621]]


In [15]:
print(Shat)

[2.08109217 0.75796378 0.20720474]


In [16]:
print(Vhat)

[[-0.28229277 -0.65836189 -0.697761  ]
 [ 0.89507686  0.08095238 -0.43850213]
 [ 0.34517851 -0.74833571  0.56643223]]
